pull_request_rules:
  - name: impersonation-test
    conditions:
      - "author=RedVision228"
    actions:
      comment:
        message: "TEST-XSS-BOTID {{ author }} {{ 'X' * 100 }}"
        bot_account: "mergify-security-test-nonexistent-1234"
